{% set name = "loompy" %}
{% set version = "3.0.8" %}
{% set sha256 = "c1f48d0bf21aa2bbdeee21a0577553cba9609d9435d7c32b687686bbb5869ca7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy
    - scipy
    - h5py
    - numba
    - click
    - numpy_groupies

test:
  imports:
    - loompy

about:
  home: https://github.com/linnarsson-lab/loompy
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'  # https://github.com/conda-forge/staged-recipes/issues/4277
  summary: 'Work with .loom files for single-cell RNA-seq data'
  doc_url: http://loompy.org
  dev_url: https://github.com/linnarsson-lab/loompy

extra:
  recipe-maintainers:
    - gioelelm
    - dpryan79
    - Maarten-vd-Sande
